from abc import ABC, abstractmethod
from typing import Any, Literal

from docker.models.containers import Container

from app.modules.interfaces.types.options import BaseContext, ScannerTaskResult
from modules.interfaces.types.context import ScanContext

# Scanner Interfaces
class IBaseScanner(ABC):
    """
        Base scanner interface.

        This interface can be implemented to derive custom scanner behavior;
        see IContainerScanner and IHeadlessScanner.

        In some cases, there maybe scanners that interact with a single container
        that is spawned on startup; see ZapScanner.
        If so, you should implement this interface instead of IContainerScanner or its
        implementors.
        """
    scanner_name: str
    scanner_type: Literal["cli", "container", "api"]
    phase: str
    report_path: str
    _scanner_context: BaseContext

    @abstractmethod
    def start_scan(self, session_id: str, ctx: ScanContext) -> ScannerTaskResult | dict:
        """
        Starts a tool scan. The return type is hinted as of type dict but the object ScannerTaskResult is required
        for the system to communicate properly
        :param session_id: Session ID for the current scan
        :param ctx: The Scan Context object
        :return: ScannerTaskResult in dictionary format
        """
        pass

    @abstractmethod
    def parse_results(self, session_id: str) -> dict | None:
        """
        Parse the tools results.
        :param session_id: Session ID for the current scan
        :returns: Parsed results
        """
        pass

    @abstractmethod
    def cleanup(self, session_id: str) -> None:
        """
        Cleans up any files, containers, and other artifacts generated by the scanner.
        It is recommended to run this function at the end of {parse_results}
        :param session_id: The session ID
        :return:
        """
        pass

class ICliScanner(IBaseScanner):
    @abstractmethod
    def build_command(self, session_id: str, ctx: ScanContext) -> list[str]:
        pass

class IContainerScanner(IBaseScanner):
    @abstractmethod
    def spawn_container(self, session_id:str, ctx: ScanContext) -> Container:
        pass

    @abstractmethod
    def spawn_headless_container(self, session_id:str, ctx: ScanContext) -> Container:
        pass

class IAPIScanner(IBaseScanner):
    @abstractmethod
    def submit_scan(self, session_id: str, ctx: ScanContext) -> str:
        pass

    @abstractmethod
    def poll_scan(self, scan_ref: str) -> dict:
        pass

class IPhaseScanner(IBaseScanner):

    @abstractmethod
    def start_scan(
            self,
            session_id: str,
            ctx: ScanContext,
            previous_context: BaseContext = None) -> ScannerTaskResult:
        pass

# === Normalizers interfaces ===

class INormalizer(ABC):
    @abstractmethod
    def normalize(self, data: Any) -> dict:
        """
        Normalizes the data to a specific structure.
        :param data: Data to be normalized
        :return: data normalized in JSON format
        """
        pass

# === Config interfaces ===

class IConfigBuilder(ABC):
    @abstractmethod
    def build(self):
        """
        Builds the configuration.
        The return type of this function should be implemented by the subclass.
        :return: config
        """
        pass