from abc import ABC, abstractmethod

from docker.models.containers import Container

from app.modules.interfaces.options import BaseContext

# === Scanner Interfaces ===

class IScanner(ABC):
    """
    Base scanner interface.

    This interface can be implemented to derive custom scanner behavior;
    see IContainerScanner and IHeadlessScanner.

    In some cases, there maybe scanners that interact with a single container
    that is spawned on startup; see ZapScanner.
    If so, you should implement this interface instead of IContainerScanner or its
    implementors.
    """
    _base_report_path: str
    _prefix: str
    _scanner_context: BaseContext

    @abstractmethod
    def start_scan(self, session_id: str, ctx: BaseContext) -> dict:
        pass

    @abstractmethod
    def _parse_results(self, session_id: str) -> dict:
        pass

    @abstractmethod
    def _cleanup(self, session_id: str) -> None:
        """
        Cleans up any files, containers, and other artifacts generated by the scanner.
        It is recommended to run this function at the end of {parse_results}
        :param session_id: The session ID
        :return:
        """
        pass

class IContainerScanner(IScanner):
    """This interface should be used implemented by scanners that spawn docker containers."""

    @abstractmethod
    def _spawn(self, container_name: str, ctx: BaseContext) -> Container:
        """
        Spawns and runs a docker container associated with the scanner.
        :param container_name: Name of the container
        :param ctx: The discovery context
        :return: The docker container object
        """
        pass

class IHeadlessScanner(IContainerScanner):
    """This interface should be used implemented by scanners that spawn docker containers that may be headless."""

    @abstractmethod
    def _spawn_headless(self, container_name: str, ctx: BaseContext) -> Container:
        """
        Spawns and runs a docker container associated with the scanner.
        This function should be implemented by the subclass when the scanner supports a headless mode.
        :param container_name: Name of the container
        :param ctx: The discovery context
        :return: The docker container object
        """
        pass

# === Normalizers interfaces ===

class INormalizer(ABC):
    @abstractmethod
    def normalize(self, data: any) -> dict:
        """
        Normalizes the data to a specific structure.
        :param data: Data to be normalized
        :return: data normalized in JSON format
        """
        pass

# === Config interfaces ===

class IConfigBuilder(ABC):
    @abstractmethod
    def build(self):
        """
        Builds the configuration.
        The return type of this function should be implemented by the subclass.
        :return: config
        """
        pass